-- jtag_bridge_system.vhd

-- Generated using ACDS version 25.1 1129

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity jtag_bridge_system is
	port (
		capture_buffer_0_conduit_end_data_in    : in std_logic_vector(7 downto 0) := (others => '0'); -- capture_buffer_0_conduit_end.data_in
		capture_buffer_0_conduit_end_data_valid : in std_logic                    := '0';             --                             .data_valid
		clk_clk                                 : in std_logic                    := '0';             --                          clk.clk
		reset_reset_n                           : in std_logic                    := '0'              --                        reset.reset_n
	);
end entity jtag_bridge_system;

architecture rtl of jtag_bridge_system is
	component capture_buffer is
		generic (
			BUFFER_ADDR_BITS : integer := 13
		);
		port (
			clk            : in  std_logic                     := 'X';             -- clk
			reset          : in  std_logic                     := 'X';             -- reset
			av_chipselect  : in  std_logic                     := 'X';             -- chipselect
			av_address     : in  std_logic_vector(13 downto 0) := (others => 'X'); -- address
			av_read_n      : in  std_logic                     := 'X';             -- read_n
			av_write_n     : in  std_logic                     := 'X';             -- write_n
			av_writedata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			av_readdata    : out std_logic_vector(31 downto 0);                    -- readdata
			av_waitrequest : out std_logic;                                        -- waitrequest
			data_in        : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- data_in
			data_valid     : in  std_logic                     := 'X'              -- data_valid
		);
	end component capture_buffer;

	component jtag_bridge_system_master_0 is
		generic (
			USE_PLI     : integer := 0;
			PLI_PORT    : integer := 50000;
			FIFO_DEPTHS : integer := 2
		);
		port (
			clk_clk              : in  std_logic                     := 'X';             -- clk
			clk_reset_reset      : in  std_logic                     := 'X';             -- reset
			master_address       : out std_logic_vector(31 downto 0);                    -- address
			master_readdata      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			master_read          : out std_logic;                                        -- read
			master_write         : out std_logic;                                        -- write
			master_writedata     : out std_logic_vector(31 downto 0);                    -- writedata
			master_waitrequest   : in  std_logic                     := 'X';             -- waitrequest
			master_readdatavalid : in  std_logic                     := 'X';             -- readdatavalid
			master_byteenable    : out std_logic_vector(3 downto 0);                     -- byteenable
			master_reset_reset   : out std_logic                                         -- reset
		);
	end component jtag_bridge_system_master_0;

	component jtag_bridge_system_mm_interconnect_0 is
		port (
			clk_0_clk_clk                                      : in  std_logic                     := 'X';             -- clk
			capture_buffer_0_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			master_0_clk_reset_reset_bridge_in_reset_reset     : in  std_logic                     := 'X';             -- reset
			master_0_master_address                            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			master_0_master_waitrequest                        : out std_logic;                                        -- waitrequest
			master_0_master_byteenable                         : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			master_0_master_read                               : in  std_logic                     := 'X';             -- read
			master_0_master_readdata                           : out std_logic_vector(31 downto 0);                    -- readdata
			master_0_master_readdatavalid                      : out std_logic;                                        -- readdatavalid
			master_0_master_write                              : in  std_logic                     := 'X';             -- write
			master_0_master_writedata                          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			capture_buffer_0_av_address                        : out std_logic_vector(13 downto 0);                    -- address
			capture_buffer_0_av_write                          : out std_logic;                                        -- write
			capture_buffer_0_av_read                           : out std_logic;                                        -- read
			capture_buffer_0_av_readdata                       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			capture_buffer_0_av_writedata                      : out std_logic_vector(31 downto 0);                    -- writedata
			capture_buffer_0_av_waitrequest                    : in  std_logic                     := 'X';             -- waitrequest
			capture_buffer_0_av_chipselect                     : out std_logic                                         -- chipselect
		);
	end component jtag_bridge_system_mm_interconnect_0;

	component altera_reset_controller is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_in1      : in  std_logic := 'X'; -- reset
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component altera_reset_controller;

	signal master_0_master_readdata                              : std_logic_vector(31 downto 0); -- mm_interconnect_0:master_0_master_readdata -> master_0:master_readdata
	signal master_0_master_waitrequest                           : std_logic;                     -- mm_interconnect_0:master_0_master_waitrequest -> master_0:master_waitrequest
	signal master_0_master_address                               : std_logic_vector(31 downto 0); -- master_0:master_address -> mm_interconnect_0:master_0_master_address
	signal master_0_master_read                                  : std_logic;                     -- master_0:master_read -> mm_interconnect_0:master_0_master_read
	signal master_0_master_byteenable                            : std_logic_vector(3 downto 0);  -- master_0:master_byteenable -> mm_interconnect_0:master_0_master_byteenable
	signal master_0_master_readdatavalid                         : std_logic;                     -- mm_interconnect_0:master_0_master_readdatavalid -> master_0:master_readdatavalid
	signal master_0_master_write                                 : std_logic;                     -- master_0:master_write -> mm_interconnect_0:master_0_master_write
	signal master_0_master_writedata                             : std_logic_vector(31 downto 0); -- master_0:master_writedata -> mm_interconnect_0:master_0_master_writedata
	signal mm_interconnect_0_capture_buffer_0_av_chipselect      : std_logic;                     -- mm_interconnect_0:capture_buffer_0_av_chipselect -> capture_buffer_0:av_chipselect
	signal mm_interconnect_0_capture_buffer_0_av_readdata        : std_logic_vector(31 downto 0); -- capture_buffer_0:av_readdata -> mm_interconnect_0:capture_buffer_0_av_readdata
	signal mm_interconnect_0_capture_buffer_0_av_waitrequest     : std_logic;                     -- capture_buffer_0:av_waitrequest -> mm_interconnect_0:capture_buffer_0_av_waitrequest
	signal mm_interconnect_0_capture_buffer_0_av_address         : std_logic_vector(13 downto 0); -- mm_interconnect_0:capture_buffer_0_av_address -> capture_buffer_0:av_address
	signal mm_interconnect_0_capture_buffer_0_av_read            : std_logic;                     -- mm_interconnect_0:capture_buffer_0_av_read -> mm_interconnect_0_capture_buffer_0_av_read:in
	signal mm_interconnect_0_capture_buffer_0_av_write           : std_logic;                     -- mm_interconnect_0:capture_buffer_0_av_write -> mm_interconnect_0_capture_buffer_0_av_write:in
	signal mm_interconnect_0_capture_buffer_0_av_writedata       : std_logic_vector(31 downto 0); -- mm_interconnect_0:capture_buffer_0_av_writedata -> capture_buffer_0:av_writedata
	signal rst_controller_reset_out_reset                        : std_logic;                     -- rst_controller:reset_out -> [capture_buffer_0:reset, mm_interconnect_0:capture_buffer_0_reset_reset_bridge_in_reset_reset, mm_interconnect_0:master_0_clk_reset_reset_bridge_in_reset_reset]
	signal reset_reset_n_ports_inv                               : std_logic;                     -- reset_reset_n:inv -> [master_0:clk_reset_reset, rst_controller:reset_in0]
	signal mm_interconnect_0_capture_buffer_0_av_read_ports_inv  : std_logic;                     -- mm_interconnect_0_capture_buffer_0_av_read:inv -> capture_buffer_0:av_read_n
	signal mm_interconnect_0_capture_buffer_0_av_write_ports_inv : std_logic;                     -- mm_interconnect_0_capture_buffer_0_av_write:inv -> capture_buffer_0:av_write_n

begin

	capture_buffer_0 : component capture_buffer
		generic map (
			BUFFER_ADDR_BITS => 13
		)
		port map (
			clk            => clk_clk,                                               --       clock.clk
			reset          => rst_controller_reset_out_reset,                        --       reset.reset
			av_chipselect  => mm_interconnect_0_capture_buffer_0_av_chipselect,      --          av.chipselect
			av_address     => mm_interconnect_0_capture_buffer_0_av_address,         --            .address
			av_read_n      => mm_interconnect_0_capture_buffer_0_av_read_ports_inv,  --            .read_n
			av_write_n     => mm_interconnect_0_capture_buffer_0_av_write_ports_inv, --            .write_n
			av_writedata   => mm_interconnect_0_capture_buffer_0_av_writedata,       --            .writedata
			av_readdata    => mm_interconnect_0_capture_buffer_0_av_readdata,        --            .readdata
			av_waitrequest => mm_interconnect_0_capture_buffer_0_av_waitrequest,     --            .waitrequest
			data_in        => capture_buffer_0_conduit_end_data_in,                  -- conduit_end.data_in
			data_valid     => capture_buffer_0_conduit_end_data_valid                --            .data_valid
		);

	master_0 : component jtag_bridge_system_master_0
		generic map (
			USE_PLI     => 0,
			PLI_PORT    => 50000,
			FIFO_DEPTHS => 2
		)
		port map (
			clk_clk              => clk_clk,                       --          clk.clk
			clk_reset_reset      => reset_reset_n_ports_inv,       --    clk_reset.reset
			master_address       => master_0_master_address,       --       master.address
			master_readdata      => master_0_master_readdata,      --             .readdata
			master_read          => master_0_master_read,          --             .read
			master_write         => master_0_master_write,         --             .write
			master_writedata     => master_0_master_writedata,     --             .writedata
			master_waitrequest   => master_0_master_waitrequest,   --             .waitrequest
			master_readdatavalid => master_0_master_readdatavalid, --             .readdatavalid
			master_byteenable    => master_0_master_byteenable,    --             .byteenable
			master_reset_reset   => open                           -- master_reset.reset
		);

	mm_interconnect_0 : component jtag_bridge_system_mm_interconnect_0
		port map (
			clk_0_clk_clk                                      => clk_clk,                                           --                                    clk_0_clk.clk
			capture_buffer_0_reset_reset_bridge_in_reset_reset => rst_controller_reset_out_reset,                    -- capture_buffer_0_reset_reset_bridge_in_reset.reset
			master_0_clk_reset_reset_bridge_in_reset_reset     => rst_controller_reset_out_reset,                    --     master_0_clk_reset_reset_bridge_in_reset.reset
			master_0_master_address                            => master_0_master_address,                           --                              master_0_master.address
			master_0_master_waitrequest                        => master_0_master_waitrequest,                       --                                             .waitrequest
			master_0_master_byteenable                         => master_0_master_byteenable,                        --                                             .byteenable
			master_0_master_read                               => master_0_master_read,                              --                                             .read
			master_0_master_readdata                           => master_0_master_readdata,                          --                                             .readdata
			master_0_master_readdatavalid                      => master_0_master_readdatavalid,                     --                                             .readdatavalid
			master_0_master_write                              => master_0_master_write,                             --                                             .write
			master_0_master_writedata                          => master_0_master_writedata,                         --                                             .writedata
			capture_buffer_0_av_address                        => mm_interconnect_0_capture_buffer_0_av_address,     --                          capture_buffer_0_av.address
			capture_buffer_0_av_write                          => mm_interconnect_0_capture_buffer_0_av_write,       --                                             .write
			capture_buffer_0_av_read                           => mm_interconnect_0_capture_buffer_0_av_read,        --                                             .read
			capture_buffer_0_av_readdata                       => mm_interconnect_0_capture_buffer_0_av_readdata,    --                                             .readdata
			capture_buffer_0_av_writedata                      => mm_interconnect_0_capture_buffer_0_av_writedata,   --                                             .writedata
			capture_buffer_0_av_waitrequest                    => mm_interconnect_0_capture_buffer_0_av_waitrequest, --                                             .waitrequest
			capture_buffer_0_av_chipselect                     => mm_interconnect_0_capture_buffer_0_av_chipselect   --                                             .chipselect
		);

	rst_controller : component altera_reset_controller
		generic map (
			NUM_RESET_INPUTS          => 1,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 0,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_reset_n_ports_inv,        -- reset_in0.reset
			clk            => clk_clk,                        --       clk.clk
			reset_out      => rst_controller_reset_out_reset, -- reset_out.reset
			reset_req      => open,                           -- (terminated)
			reset_req_in0  => '0',                            -- (terminated)
			reset_in1      => '0',                            -- (terminated)
			reset_req_in1  => '0',                            -- (terminated)
			reset_in2      => '0',                            -- (terminated)
			reset_req_in2  => '0',                            -- (terminated)
			reset_in3      => '0',                            -- (terminated)
			reset_req_in3  => '0',                            -- (terminated)
			reset_in4      => '0',                            -- (terminated)
			reset_req_in4  => '0',                            -- (terminated)
			reset_in5      => '0',                            -- (terminated)
			reset_req_in5  => '0',                            -- (terminated)
			reset_in6      => '0',                            -- (terminated)
			reset_req_in6  => '0',                            -- (terminated)
			reset_in7      => '0',                            -- (terminated)
			reset_req_in7  => '0',                            -- (terminated)
			reset_in8      => '0',                            -- (terminated)
			reset_req_in8  => '0',                            -- (terminated)
			reset_in9      => '0',                            -- (terminated)
			reset_req_in9  => '0',                            -- (terminated)
			reset_in10     => '0',                            -- (terminated)
			reset_req_in10 => '0',                            -- (terminated)
			reset_in11     => '0',                            -- (terminated)
			reset_req_in11 => '0',                            -- (terminated)
			reset_in12     => '0',                            -- (terminated)
			reset_req_in12 => '0',                            -- (terminated)
			reset_in13     => '0',                            -- (terminated)
			reset_req_in13 => '0',                            -- (terminated)
			reset_in14     => '0',                            -- (terminated)
			reset_req_in14 => '0',                            -- (terminated)
			reset_in15     => '0',                            -- (terminated)
			reset_req_in15 => '0'                             -- (terminated)
		);

	reset_reset_n_ports_inv <= not reset_reset_n;

	mm_interconnect_0_capture_buffer_0_av_read_ports_inv <= not mm_interconnect_0_capture_buffer_0_av_read;

	mm_interconnect_0_capture_buffer_0_av_write_ports_inv <= not mm_interconnect_0_capture_buffer_0_av_write;

end architecture rtl; -- of jtag_bridge_system
